### ISSUE TITLE
Random signing fails

### ISSUE THREAD

**Issue by jjxtra** [scottbrady91/AspNetCore-SignInWithApple-Example#1]
About one time in three I get this error:

```
 ---> Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key:
kid: '***'.

token: '{"alg":"RS256","kid":"***"}.{"iss":"https://appleid.apple.com","aud":"***","exp":1584977066,"iat":1584976466,"sub":"***","at_hash":"***","auth_time":1584976464,"nonce_supported":true}'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateToken(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters, JwtSecurityToken& jwt)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Not sure why, any ideas?

**Comment by jjxtra** [comment]
Fixes:

For debug locally, modify hosts file:
```
127.0.0.1 your-apple-sign-in-domain.com
```
Then set your vs debug settings to use this for site url, i.e. http://your-apple-sign-in-domain.com

For setting signing keys, apple has multiple now:
```
var webSet = new JsonWebKeySet(jwks);
options.TokenValidationParameters.IssuerSigningKeys = webSet.Keys;
```

For scopes:
```
options.Scope.Clear();
options.Scope.Add("name");
options.Scope.Add("email");
options.Scope.Add("openid");
```

For cookies (these are debug settings, for production obviously you would not do ssl and same site mode this way):
```
app.UseCookiePolicy(new CookiePolicyOptions()
{
    HttpOnly = HttpOnlyPolicy.Always,
    Secure = CookieSecurePolicy.None,
    MinimumSameSitePolicy = SameSiteMode.None
});
```

**Comment by scottbrady91** [comment]
Glad to hear you got it working 🙂
